---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: multi-pod
  name: multi-pod
spec:
  containers:
  - image: nginx
    name: alpha
    resources: {}
    env:
    - name: alpha
      value: "alpha"
  - command:
    - sleep
    - "4800"
    image: busybox
    name: beta
    resources: {}
    env:
    - name: beta
      value: "beta"
  dnsPolicy: ClusterFirst
  restartPolicy: Always