---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: lookup
  name: lookup
spec:
  containers:
  - command:
    - "sh"
    - "-c"
    - "sleep 3600"
    image: busybox:1.28
    name: lookup
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
