---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-alpha-claim
  namespace: alpha
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: slow
  volumeMode: Filesystem